### ISSUE TITLE
dialog内容不支持换行，也不支持样式自定义

### ISSUE THREAD

**Issue by yuzhou423** [jwaterwater/vue-layer-mobile#2]
内容样式自定义方面可能有点难度，但是内容换行方面，可不可以完善一下，因为在内容里content添加\n\r貌似都不管用，作者有没有好点的办法？

**Comment by jwaterwater** [comment]
我做了修改，你可以更新下包再试一下，现在dialog的content可以自定义class，并支持<br>换行，content内支持任意html

**Comment by yuzhou423** [comment]
现在已经支持换行了，但是更新了版本，页面有报错！
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'   main.js?ae67:202

**Comment by HarrisFeng** [comment]
发布新版本请更新版本号，这样即便报错也可以装旧版本解决，现在覆盖安装。。。。。。。昨天还好好的，今天就跪了

**Comment by jwaterwater** [comment]
不好意思，我来找下问题，因为发布前我本地测试下没问题就发布了

**Comment by jwaterwater** [comment]
想回旧版本就执行npm install vue-layer-mobile@1.0.0

**Comment by yuzhou423** [comment]
嗯嗯，主要还是因为发布时版本号的问题吧，跟代码没太多关系，所以，你本地测试是没问题的，但是别人更新了之后就会出问题，主要是npm run build的时候报错，npm run dev 时是没问题的，另外，contentClass这个属性貌似没生效，我审查元素了，页面代码里面有这个class属性，但是对应的样式却没有显示出来，不清楚是什么原因！

**Comment by jwaterwater** [comment]
大家可以再试试新版，这次把文件编译了。
